### ISSUE TITLE
"No purchases available"

### ISSUE THREAD

**Issue by dordsor21** [WooMinecraft/woominecraft-wp#26]
the "No purchases available - please try again soon." is returned, despite purchases having been made. Submitted a PR to check whether it's a lack of an HTTP response, but for the moment, it could be anything :)

**Comment by JayWood** [comment]
No need for the PR, the HTTP response - the purchase set was empty on the server side according to your DEBUG log

`[00:58:46 INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":[]}`

It's a JSON string, and Data was empty, which means the server didn't send any pending commands. Quite possibly due to the older dev version before now.  Also, if we could just keep the issue in one place that'd be great 😄 

Closing this in favor of WooMinecraft/WooMinecraft#136
